-- CURDATE()
SELECT CURDATE() AS 'Data Atual';

-- CURTIME()
SELECT CURTIME() AS 'Hora Atual';

-- CURRENT_TIME()
SELECT CURRENT_TIME() AS 'Hora Atual';

-- DATE_ADD(data, interval)
SELECT DATE_ADD(CURDATE(), INTERVAL 3 DAY) AS 'Data de Vencimento';

-- DATE_SUB(data, interval)
SELECT DATE_SUB(CURDATE(), INTERVAL 10 DAY) AS 'Data de Matrícula';

-- DATEDIFF(expre1, expre2)
SELECT DATEDIFF(CURDATE(), DATE_SUB(CURDATE(), INTERVAL 10 DAY)) AS 'Dias em Atraso';

-- DATE_FORMAT
SELECT DATE_FORMAT(CURDATE(), '%d/%m%/%Y') AS 'Data Atual';

-- DAY_NAME
SELECT DAYNAME(CURDATE()) AS 'Dia da Semana';

-- DAYOFMONTH
SELECT DAYOFMONTH(CURDATE()) AS 'Dia do Mês';

-- DAYOFWEEK
SELECT DAYOFWEEK(CURDATE()) AS 'Dia da Semana';

-- DAYOFYEAR
SELECT DAYOFYEAR(CURDATE()) AS 'Dia do Ano';

-- FROM_DAYS
SELECT FROM_DAYS(709377) AS 'Data Real';

-- NOW 
SELECT NOW() AS 'Data/Hora Atual';

SELECT DATE_FORMAT(NOW(), '%d/%m/%Y %H:%i:%s') AS 'Data/Hora Atual';

SELECT DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%m/%Y %H:%i:%s') AS 'Data/Hora Atual';

-- Time
SELECT TIME (CURRENT_TIMESTAMP()) AS 'Hora';

-- SEC_TO_TIME
SELECT SEC_TO_TIME(2000) AS 'Tempo Total';

-- TIME_TO_SEC
SELECT TIME_TO_SEC(TIME(CURRENT_TIMESTAMP())) AS 'Tempo em segundos';

SELECT HOUR(TIME(CURRENT_TIMESTAMP())) AS Hora, 
MINUTE(TIME(CURRENT_TIMESTAMP())) AS Minutos, 
SECOND(TIME(CURRENT_TIMESTAMP())) AS Segundos;

-- PERIOD_DIFF
SELECT period_diff(202512, 202504) AS 'Meses Restantes';

-- TIME_DIFF
SELECT TIMEDIFF('12:35:34', '12:30:46') AS Diferença;

-- QUARTER
SELECT QUARTER('2025-04-28') AS 'Trimestre do ano';

-- SELECT WEEK
SELECT WEEK('2025-04-28') AS 'Semana do ano';

-- SELECT WEEKDAY
SELECT WEEKDAY('2025-04-28') AS 'Dia da Semana';

-- SELECT YEAR
SELECT YEAR('2025-04-28') AS 'Ano';

-- SELECT MONTH
SELECT MONTH(NOW()) AS 'Ano';

-- SELECT DAY
SELECT DAY(NOW()) AS 'Dia';

